### ISSUE TITLE
Tweaks to Contentful blog backend/presentation

### ISSUE THREAD

**Issue by stichbury** [kedro-org/kedro-website#97]
I've uploaded the very first blog post to Contentful, and it's looking awesome. I had a few minor feedback issues that I thought I'd share here for discussion. Have also shared a link to the post with @Mackay031 to review it.

Q1: I did a copy/paste of all the content from a Word file. There's quite a lot of whitespace above each H2, and I've removed extra spacing in the backend but it's still showing that way. Is it maybe too much?

Q2. I would like to be able to include links in the asset Title (since for a graphic, that becomes the caption, and we need to link to the author/creative commons licence for the asset). Would it be possible to add that, or alternatively to add a caption field which can include links, and surface that as the graphic caption instead of the Title?

Q3. I've added @NeroOkwa as an author but I can't click on his photo/name and go to a page with a list of what else he's written on the blog and more about his bio. But I can get to that info from the main blog page which lists all the blog posts...so maybe this is a bug?

**Comment by tynandebold** [comment]
I've just addressed your second and third questions.

For the second question, see the new Media content type [here](https://app.contentful.com/spaces/zwej9aiux6b9/entries/3UDDb4MCZD4sdPnRNC0m6D). You'll use an already-uploaded image and add that in. The caption is now a Rich Text field, so can take links and whatever else you'd like.

For the third, you can now click on Nero's name [here](https://deploy-preview-63--kedro-website.netlify.app/blog/experiment-tracking-with-kedro).

@Mackay031 will have to speak to the first question. That's how it was designed, so I don't think it's a question of dev implementation.

**Comment by stichbury** [comment]
Thanks @tynandebold that's fantastic. I'll hand over to @Mackay031 to see what he thinks overall of the post now (in preview, link to be shared separately) and raise any further points.

**Comment by stichbury** [comment]
@tynandebold Just a quick query -- I've noticed that the image asset of the experiment tracking screen (gif) has disappeared from the page (it's in the backend but isn't surfacing properly). I deleted it in the backend and re-added it, but still not there. Please could you take a look?

**Comment by stichbury** [comment]
@Mackay031 @tynandebold I've now updated the post in the backend following your comments on Figma. There are now 3 GIF assets uploaded but none are showing as per the Netlify issue above.

When you've a moment, please could you take a look at the layout @Mackay031 to see if that now meets your design. 

Do you want me to raise an issue about the link-opening in new tab discussion?

**Comment by tynandebold** [comment]
The blockquotes don't look right. They should look like this: 

<img width="988" alt="image" src="https://user-images.githubusercontent.com/16869061/226918377-09743678-da22-41d8-b29c-fdf505478eb1.png">

They're missing an attribution, and since they don't have one, they're taking the attribution's style, which is small and not at all like a quote.

Can we add an attribution to them or do you envision there will often be times when you want a quote without an attribution under it, and will be in the text body, as you've done it here?

For the new tab/same tab, let me see if I can solve that quickly now without a ticket.

**Comment by Mackay031** [comment]
Ok I see. Could the whole of content section below the header animate up as one big block? The problem we have now is thats its half & half. ie. the header animates in after the content. If thats a big job, then could we have the header section not animate for the blog post page so it doesn't look like an error.

**Comment by stichbury** [comment]
@tynandebold When it comes to the pull quote that you mention above, I don't see where to add attribution.

I'm using the following method to add the text into the post:

<img width="737" alt="image" src="https://user-images.githubusercontent.com/5180475/227216389-cc6b38aa-66fd-4625-9914-2d8b357c9870.png">

That's just a button to highlight text and format it.

Is that correct? I don't see anything called "pull quote" in the "Embed > Entry" or "Embed > Inline entry" options so I'm not creating a separate item in the post.

![image](https://user-images.githubusercontent.com/5180475/227216733-578267b6-2823-4fee-89e3-f6c0f9010455.png)

**Comment by tynandebold** [comment]
Sorry this is a little confusing. The attribution should go on a second line. Like so:

![Screenshot 2023-03-23 at 13 25 15](https://user-images.githubusercontent.com/16869061/227218235-f8b0bc91-79bc-4720-ab9a-fa31b3c86f8a.png)

**Comment by stichbury** [comment]
💥 that works. Thank you!
